### ISSUE TITLE
iSponsorBlockTV add-on error: Task exception was never retrieved

### ISSUE THREAD

**Issue by Niek** [bertybuttface/addons#19]
Not sure if this is an error with the HA addon or with the iSponsorBlockTV add-on, but I see these errors:

```
Getting segments for next video: ji5HwS3bhlU
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-63' coro=<AsyncConditionalTTL.__call__.<locals>.wrapper() done, defined at /usr/app/iSponsorBlockTV/conditional_ttl_cache.py:75> exception=TypeError('ApiHelper.process_segments() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/usr/app/iSponsorBlockTV/conditional_ttl_cache.py", line 80, in wrapper
    self.ttl[key] = await func(*args, **kwargs)
  File "/usr/app/iSponsorBlockTV/api_helpers.py", line 124, in get_segments
    return self.process_segments(response)
TypeError: ApiHelper.process_segments() takes 1 positional argument but 2 were given
Getting segments for next video: ji5HwS3bhlU
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-90' coro=<AsyncConditionalTTL.__call__.<locals>.wrapper() done, defined at /usr/app/iSponsorBlockTV/conditional_ttl_cache.py:75> exception=TypeError('ApiHelper.process_segments() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/usr/app/iSponsorBlockTV/conditional_ttl_cache.py", line 80, in wrapper
    self.ttl[key] = await func(*args, **kwargs)
  File "/usr/app/iSponsorBlockTV/api_helpers.py", line 124, in get_segments
    return self.process_segments(response)
TypeError: ApiHelper.process_segments() takes 1 positional argument but 2 were given
```

**Comment by dmunozv04** [comment]
It’s an issue with that specific commit. A new version of the add on should be released that gets the latest changes from upstream, which should fix this

**Comment by Niek** [comment]
Thanks, hopefully @bertybuttface can bump the upstream version.

**Comment by bertybuttface** [comment]
Done

2.0.7 is building now.

**Comment by Niek** [comment]
I can confirm this fixed it, thanks a lot!

**Comment by dmunozv04** [comment]
That’s great news!
